import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import RootProviders from '@/context/RootProvider';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Kumbio App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<RootProviders>{children}</RootProviders>
			</body>
		</html>
	);
}
