name: Semantic Release CI/CD Workflow

on:
  push:
    branches:
      - release

jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Merge Release into Main
        run: |
          git fetch
          git checkout main
          git merge --no-ff origin/release --no-edit
          git push origin main
